name: Pull Request

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**

jobs:
  ci:
    name: continuous integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.2.0
        with:
            ci: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
