name: Pull Request

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: continuous integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - uses: pre-commit/action@v3.0.1
