name: Main Release

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  ci:
    name: semantic release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
